### ISSUE TITLE
https vs http - {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

### ISSUE THREAD

**Issue by Janpopan** [cnescatlab/sonar-cnes-report#127]
### Expected behavior
The plugin works at a server with only https, like at a server with http.

### Actual behavior
The pluing tries to call itself http://bla.blub/... at the ui you see {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}. in the log you see ein error while trying to connct the http url, because the server has only https

### Steps to reproduce behavior
see abover
### Detection version
latetest from the Marketplace + Sonar 7.9.1

**Comment by Sancretor** [comment]
Hi @Janpopan !

Thank you for your feedback, we appreciate it !  
We will look into it as soon as possible.

**Comment by Sancretor** [comment]
Hi @Janpopan !

I just made a small test with the plugin and a SonarQube only accepting HTTPS connections.
For me, everythings works fine with HTTPS.
The plugin uses a SonarQube internal property to create the URL, so if you use https in your browser, it should do the same.
Could you check it's not an issue related with your proxy configuration ?

**Comment by Sancretor** [comment]
Just to let you know that we just released a new version compatible with 8.9 LTS.
We completely changed the way the plugin handles API calls.
It now uses internal SonarQube classes instead of localhost http calls, so it may resolve your issue.

Please let us know if it doesn't.
