### ISSUE TITLE
Report doesn't include Security Hotspots

### ISSUE THREAD

**Issue by komodikkio** [cnescatlab/sonar-cnes-report#133]
Hello and thank you for the very nice project
I'm testing this plugin on a SonarQube 8 CE setup and i cannot find security hotspots data, which I can find in the web ui, on the exported reports.
Reading this https://github.com/lequal/sonar-cnes-report/issues/56 and the other linked issues, i thought this was already present in 3.x plugin
Am i missing something?
Thanks in advance and excuse me if I made any mistake in this thread, but is my first post here 

Following the details about my setup:
Sonarqube version: 8.2.0.32929 Community Edition
sonar-cnes-report plugin version: 3.2.2

### Expected behavior
When exporting the reports archive, security hotspots data can be found in report files

### Actual behavior
Even if security hotspots are present in web ui
[![Sec-Hotspots.jpg](https://i.postimg.cc/8CTRH8tx/Sec-Hotspots.jpg)](https://postimg.cc/NKP2snhx)

the info cannot be found in exported files
[![available.png](https://i.postimg.cc/52C27pPJ/available.png)](https://postimg.cc/Snm4jLF1)

### Steps to reproduce behavior
In SonarQube create a project and scan it using sonar-scanner, maven plugin, ecc
Export the report from cnesreport tab
Open xlsx or csv file and search for hotspots

**Comment by Sancretor** [comment]
HI @komodikkio 

Thanks for your feedback, we appreciate it !
That's definitly something we have to investigate...
Security Hotspots should be available in the report, at least in the XSLX report.
I guess it was mainly tested on SonarQube 7.9 for our needs, so it might be a non working feature for 8.x ... we'll see.

**Comment by amthmsExprn** [comment]
Looks like in 8.X hotspots got its own endpoint doing a little inspection: api/hotspots/show? ... The endpoint is however not in the documentation.

**Comment by komodikkio** [comment]
Hello and thanks for your replies
Actually i moved on SQ 7.9 to make it work, but would be nice to get this working on the 8.x release of SQ.

**Comment by amthmsExprn** [comment]
I was able to prototype a new report w/ the new hotspots endpoint this morning.

**Comment by Sancretor** [comment]
Hi @amthmsExprn 
Thanks a lot for your contribution !!
Sorry for the huge delay though... I hope I'll be able to have a look at it soon.
