### ISSUE TITLE
CNES Report should be available only on server side

### ISSUE THREAD

**Issue by begarco** [cnescatlab/sonar-cnes-report#137]
#### Is your feature request related to a problem? Please describe.
> _A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

When using sonar-scanner we can see in the log messages that CNES Report is loaded: it shouldn't because it is useless.

#### Describe the solution you'd like
> _A clear and concise description of what you want to happen._

Prevent sonar-scanner to download and load CNES Report.

Simply add a condition on the SonarQube environment in the `ReportPlugin.define()` method. It should be available only on server side.

**Comment by Sancretor** [comment]
Hi @begarco 

I tried to use the `@ServerSide` annotation to prevent SonarScanner from loading the plugin but it did not work.
Also, I can't find a way to determine on which environment the code is working...
Moreover, adding the extensions loading inside a condition that is false does not change a thing...
It always calls the `ReportSonarPlugin.define()` method.

What was your idea regarding this issue ?
