### ISSUE TITLE
Configurable template in web UI

### ISSUE THREAD

**Issue by begarco** [cnescatlab/sonar-cnes-report#138]
#### Is your feature request related to a problem? Please describe.
> _A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

As command line tool, CNES Report allow to set the template for reports: it should be available in sonar plugin too.

#### Describe the solution you'd like
> _A clear and concise description of what you want to happen._

Add possibility to configure which template to use through web UI.

**Comment by WillNilges** [comment]
:+1: to this, I just made a custom template and would like to be able to specify it from the plugin UI.
