### ISSUE TITLE
Cannot export report "error": "This project can't be exported, please check your token."

### ISSUE THREAD

**Issue by bientt210** [cnescatlab/sonar-cnes-report#142]
Hi Team,

I'm using Sonar version 7.9.3, and CNES plugin version lastest 3.2.2, untill recently i get error when export report
"error": "This project can't be exported, please check your token."

I'm check in sonar.log but i get no error

Jun 03, 2020 12:49:51 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: Detected SonarQube version: 7.9.3 

Can someone help me to fix this issue?

Thanks you so much

**Comment by joshrasa123** [comment]
I am getting same error.
Sonar qube version used:
Enterprise EditionVersion 8.2

**Comment by Sancretor** [comment]
Hi @bientt210 

Sorry for the important delay...
You said "until recently", so does that mean you don't have the issue anymore ?
Anyway, with this kind of information, we can't do much...
Did you try to use it as a standalone command line tool instead ?

**Comment by bientt210** [comment]
Hi @Sancretor 

Thanks for answer me, 
The issue still exist but I realize that when I change all Quality Profile to default `sonar way` this issue not happen anymore. Cause by I change Quality Profile `sonar way` default  with a custom Quality Profile.

Can you fix this problem soon?

Thanks you so much.

**Comment by Sancretor** [comment]
Hi @bientt210 

Hard to say when we will be able to solve this, as we don't fully understand the issue yet.

Ok so it works with `sonar way` but not with custom profiles...
Is there any special character inside your custom Quality Profile name ? 
Like a `&` or `/` for example.

**Comment by bientt210** [comment]
Hi @Sancretor 
My custom Quality Profile name have some special character inside is #, ++ but when I change all to normal character I'm getting error `"msg": "An error has occurred. Please contact your administrator"` and when I check logs in `web.log` `java.lang.IllegalStateException: Fail to write XML: Invalid white space character (0x8) in text to output (in xml 1.1, could output as a character entity)`

Hope my information useful for you,
Thanks you

**Comment by Sancretor** [comment]
Hi @bientt210 
Indeed, I see now what the problem is. Thanks for your feedback !
Unfortunately, I can't promise it will be solved soon...
We'll do our best to find some time for this.

**Comment by pascencio** [comment]
Hi everyone,

I had the same issue with SonarQube 8.5 and Sonar CNES Report  3.2.2. I solved the problem downgrading SonarQube version to 8.4.

**Comment by Sancretor** [comment]
Hi @pascencio 

Thanks for the feedback !
You should have a look at the README though, we are not officially compatible with SQ >8.2.

**Comment by pascencio** [comment]
Yep my mistake :nerd_face:. At least, now you know that the plugin it's compatible with SQ 8.4 :stuck_out_tongue:.

Good work! your plugin is great!

**Comment by Sancretor** [comment]
You're welcome ! 
We are glad you enjoy it. :)
We do our best to maintain it with the very little time we have...

**Comment by geyuqiu** [comment]
@Sancretor are there any actions planned to support sonar versions above 8.2?

**Comment by Sancretor** [comment]
Hi @geyuqiu 
I answered your question here : https://github.com/cnescatlab/sonar-cnes-report/issues/172#issuecomment-754044625
Please prefer the use of open issues, or open a new one if needed.
