### ISSUE TITLE
Only Sonarqube admins were able to generate the CNES Reports

### ISSUE THREAD

**Issue by manideepsunny** [cnescatlab/sonar-cnes-report#145]
### Expected behavior
Users who have access to only certain projects & are not administrators in Sonarqube are unable to generate the CNES report.
When clicking the CNES Report, I am seeing a **403** for **/api/projects/search** 
### Actual behavior
Anyone with access to certain projects should be able to download the reports

### Steps to reproduce behavior
Create a user and provide sonar-user access instead of sonar-administrators and try downloading a CNES report and you will see this error.

### Detection version
3.2.2

**Comment by Sancretor** [comment]
Hi @manideepsunny 

Sorry for the important delay...
I'll have to investigate a bit, as soon as possible, because this works on our server.
It may also be good to have a look at how you manage rights on your SonarQube, in case something explicitly prevent common users to use this API.

**Comment by KylanZhang** [comment]
![image](https://user-images.githubusercontent.com/19925721/93041989-8a9ccc80-f680-11ea-8614-ec63efb1cecc.png)

**Comment by KylanZhang** [comment]
@Sancretor  none system admin can not generate the CNES Reports.
