### ISSUE TITLE
cnesreport do not support '&' in quality profile names

### ISSUE THREAD

**Issue by begarco** [cnescatlab/sonar-cnes-report#146]
### Expected behavior
The cnesreport should be able to handle any quality profile's name that SonarQube support.

### Actual behavior
If the quality profile contains '&' it is considered as parameters separator in request part of the url used in cnesreport.

### Steps to reproduce behavior
- Name a quality profile C&B
- Analyze a project with this quality profile
- Export a report

### Detection version
3.2.2

**Comment by Sancretor** [comment]
Issue related to #142
