### ISSUE TITLE
Not able to generate the CNES report

### ISSUE THREAD

**Issue by Husainm1995** [cnescatlab/sonar-cnes-report#149]
### Expected behavior
Detected SonarQube version: 7.9.3

### Actual behavior
{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]} 

### Steps to reproduce behavior
Click on more --> CNES report 
Select the project from the drop down and click on generate

### Detection version
Community EditionVersion 7.9.3 (build 33349)

I am running Sonarqube from a docker container. Installed the CNES plugin from the marketplace, restarted the server. 
Followed the procedure 
Click on more --> CNES report 
Select the project from the drop down and click on generate

Got the error {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]} 
When I checked the docker logs the error there is :

Jul 13, 2020 11:29:12 AM fr.cnes.sonar.report.providers.SonarQubeInfoProvider getSonarQubeStatus
SEVERE: Insufficient privileges error sent by SonarQube server (code 403), please check your permissions in SonarQube configuration.
fr.cnes.sonar.report.exceptions.BadSonarQubeRequestException: Insufficient privileges error sent by SonarQube server (code 403), please check your permissions in SonarQube configuration.

Jul 13, 2020 11:29:12 AM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube online: false
2020.07.13 11:29:12 ERROR web[AXNHk8IaP+SXZ1PzAACX][o.s.s.w.WebServiceEngine] Fail to process request http://XXXX:443/sonar/api/cnesreport/report?key=338049a371bebe731d8289e9aca9f75f4fb01fc5&branch=master&author=Husain&token=a2fe35290df3460aa62fa90816a4652ca5b9d486&generation=Generate
fr.cnes.sonar.report.exceptions.SonarQubeException: Impossible to reach SonarQube instance.

Kindly suggest

**Comment by Sancretor** [comment]
Hi @Husainm1995 

Than you for your feedback, we appreciate it !
An issue regarding your rights seems obvious...
Could you check that your token has sufficient rights to access the targeted project ?

Otherwise, it might be related to #145.
A workaround could be to use an admin user to generate the reports...

**Comment by Husainm1995** [comment]
I used the admin user. Still it is showing the same error.

**Comment by Sancretor** [comment]
Weird.
Are you sure the token belongs to the admin user ?
Maybe the admin user has no rights on your project, so please do check the project's permissions matrix.

I dont think it is related to the plugin as you are the only one reporting this kind of issue.

**Comment by Husainm1995** [comment]
What should be the project's permissions matrix. 
I have created a group and added my user to the group.
Now which permission should I check in order I don't face the insufficient privilege error?

**Comment by Sancretor** [comment]
Hi @Husainm1995 
I cannot say exactly, tests would have to be performed.
What I can say is that with SonarQube default configuration, at the very least the admin user is able to perform a report generation.
I don't recommend this for production setup, but you should test that with every possible permission given to your user, he is then able to use the plugin.
If not, either you have a configuration at global SonarQube level that is preventing that, or there is something else blocking your API request (front proxy ?).

**Comment by Husainm1995** [comment]
Yes there is nginx as a reverse proxy for hosting sonarqube and that is restricted to be accessed through a single IP.
Is that causing the error?

**Comment by Sancretor** [comment]
It could be the cause....
But I don't know anything about your NGINX configuration.
You have to check your nginx logs to see if it is blocking the request, and look for a way to enable it.

**Comment by Sancretor** [comment]
This issue has been closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.

Regards.
