### ISSUE TITLE
[ERROR] The 'organization' parameter is missing

### ISSUE THREAD

**Issue by mateuszk87** [cnescatlab/sonar-cnes-report#161]
#### Describe the bug

When using Sonarcloud the following error message is thrown:
**[ERROR] The 'organization' parameter is missing**

#### To reproduce
The shortest command to reproduce the issue is when some public project is used. The same applies for other projects where a token needs to be provided.

```java
java -jar sonar-cnes-report-3.2.2.jar -p apache_struts -s https://sonarcloud.io
SonarQube URL: https://sonarcloud.io
SonarQube online: true
Detected SonarQube version: 8.0.0
[ERROR] The 'organization' parameter is missing
```

#### User environment 
* OS: Linux (Docker) Linux b2a4c59376d8 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux
* Project version: [3.2.2]

**Comment by Sancretor** [comment]
Hi @mateuszk87 

Thanks for your feedback !
Unfortunately, as far as I know, we are not compatible with SonarCloud yet.
