### ISSUE TITLE
add analysisId parameter for getting a report for an analysis

### ISSUE THREAD

**Issue by csegedicsaba** [cnescatlab/sonar-cnes-report#163]
#### Is your feature request related to a problem? Please describe.

> _We need to get a report for a specified analysis_

#### Describe the solution you'd like

> _Adding an extra parameter where the analysisId  can be specified_

**Comment by begarco** [comment]
Hi @csegedicsaba,

Thanks for using cnesreport.

Nevertheless, you should refer to SonarQube official documentation: it is not possible to extract data from previous analysis, you can only export issues for last analysis of each branch.

Benoît
