### ISSUE TITLE
Plugin is not working for non-admin users

### ISSUE THREAD

**Issue by Nikhilnick1203** [cnescatlab/sonar-cnes-report#165]
#### Describe the bug

The plugin is working when I log in to SonarQube as an admin but not for non-admin users, it keeps on loading on a blank screen

#### To reproduce

> _Steps to reproduce the behavior._

1. Login as non-admin
2. Click on 'more>CNES'
3. See error

#### Expected behavior

> _A clear and concise description of what you expected to happen._

#### Screenshots & log

> _If applicable, add screenshots and logs to help explain your problem._ **Do not forget to obfuscate them if they contain sensitive data.**.
![image](https://user-images.githubusercontent.com/71391042/93347042-44976280-f852-11ea-966f-627a9e0c42db.png)

#### User environment 

> _Please complete the following information._

* OS: Windows 10
* Project version: [1.0.0]

**Comment by Nikhilnick1203** [comment]
Any update on this?

**Comment by Sancretor** [comment]
Related to #145

**Comment by aastha226** [comment]
Any update on this?
