### ISSUE TITLE
Pie chart colors specified in custom template are incorrect

### ISSUE THREAD

**Issue by WillNilges** [cnescatlab/sonar-cnes-report#166]
#### Describe the bug

It appears that colors specified in a template for the pie chart won't stay consistent. For example, if I set it up like so in the template:
![image](https://user-images.githubusercontent.com/42927786/93927741-5318ca80-fce7-11ea-954d-497906daba5e.png)

The colors appear to "shift" one to the left. So that BLOCKER is green, CRITICAL is black, and so on.

#### To reproduce

1. Create custom template with LibreOffice
2. Modify the chart colors
3. Create report on CLI using this template
4. Observe mismatched colors

#### Expected behavior

Colors line up with severity levels as specified in the template

#### User environment 

* OS: Ubuntu 20.04
* Project version: 3.2.2
* SonarQube: 8.4

**Comment by WillNilges** [comment]
Not totally sure about this, but I think the issue might be that in the template, it's sorting by severity (or alphabetically?) but when you actually generate a report, it assigns the colors by quantity and re-arranges the tags accordingly. So for example, I just generated a new report on a different repo with a lot of major issues and only one or two blockers and critical issues, and so the blockers and criticals, which on the template are assigned to the top of the pie chart, are moved to the bottom in favor of major issues, which is then colored as black because it's where blockers are supposed to be.

**Comment by Sancretor** [comment]
Hi @WillNilges 

I know it's been a very long time... but if you're still interested, you could have a look at the dev branch where the fix has just been merged.
In case you test it, don't hesitate to give us some feedback !

**Comment by WillNilges** [comment]
Hey @Sancretor ,
I found this bug during my last internship, and no longer have access to the facilities or resources required to test this. I will be returning to that position sometime in the fall, and if it comes up, I'll definitely give it a go.
Thanks for fixing this!
