### ISSUE TITLE
CNES Report not working for 8.5.1.38104 in sonaqube server.

### ISSUE THREAD

**Issue by sachithanandhampalaniswamy** [cnescatlab/sonar-cnes-report#186]
#### Describe the bug

> We had installed recent release of sonarqube 8.5.1.38104 as released [https://github.com/cnescatlab/sonar-cnes-report/releases/tag/3.3.0], but when trying to generate CNES report. An error occurred. [{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

#### To reproduce
Install 8.5.1.38104 of sonarqube and CNES report

1. Go to CNES Report menu
2. Select a project from CNES report 
3. Click Generate button
4. See error {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

#### Expected behavior

> Should able to generate a zip file , which was happening for previous version of sonarqube.

* OS: [e.g. Windows 10]

**Comment by Sancretor** [comment]
Hi @sachithanandhampalaniswamy 

Thanks for your feedback !
Unfortunately, as stated in the project README, we are not compatible with SonarQube 8.5.
Please have a look at the dedicated section : https://github.com/cnescatlab/sonar-cnes-report#compatibility-matrix

**Comment by gvuspace** [comment]
Hi @sachithanandhampalaniswamy 

See my comment https://github.com/cnescatlab/sonar-cnes-report/issues/187#issuecomment-753942657 for a temporary workaround.

**Comment by sachithanandhampalaniswamy** [comment]
@gvuspace can you share jar file with fix.

**Comment by sachithanandhampalaniswamy** [comment]
Thanks was able to generate jar file by skipping unit test mvn package -Dmaven.test.skip=true and the fix worked :). When do we can upgrade to SQ 8.6.

**Comment by gvuspace** [comment]
> @gvuspace can you share jar file with fix.

First of all, I'm no maintainer of this project. I could upload the jar I built locally, but I'm reluctant to share unofficial binary files, mostly for security reasons (how could you be sure that the jar I send was actually built from the source code of the project, and that I didn't include any malicious stuff?)


> Thanks was able to generate jar file by skipping unit test mvn package -Dmaven.test.skip=true and the fix worked :). When do we can upgrade to SQ 8.6.

Glad it worked :) FYI I used the workaround directly on 8.6, so it should work for you as well.

As for the official fix, again I'm no maintainer, but you can look at the discussion on #172. Also I would suggest moving the discussion over there and closing current issue to avoid unnecessary duplicates.

**Comment by sachithanandhampalaniswamy** [comment]
Sure @gvuspace , closing it for now.
