### ISSUE TITLE
CNES Report 3.3.0 not working for 8.6.0.39681 in sonaqube server.

### ISSUE THREAD

**Issue by rajainteq** [cnescatlab/sonar-cnes-report#187]
#### Describe the bug

> We had recently upgrade the latest release of sonarqube 8.6.0.39681 as released [https://github.com/cnescatlab/sonar-cnes-report/releases/tag/3.3.0], but when trying to generate CNES report. An error occurred. {"error":"This project can't be exported, please check your token."}

#### To reproduce

>Install 8.6.0.39681 of sonarqube and CNES report

1. Go to More and select CNES Report menu
2. Select a project from CNES report
3. Click Generate button
4. See error : {"error":"This project can't be exported, please check your token."}

#### Expected behavior

> Should able to generate a zip file , which was happening for previous version of sonarqube.

#### Screenshots & log

> 
![CNES Report-01](https://user-images.githubusercontent.com/41499320/103436757-417b8300-4c45-11eb-8093-a2c147e5ae5d.PNG)
![CNES Report](https://user-images.githubusercontent.com/41499320/103436732-fd887e00-4c44-11eb-86c9-d0deac4f45c0.PNG)

#### User environment 

> _Please complete the following information._

* OS: [Windows Server 2019 Data Center]
* Project version: [3.3.0]

**Comment by Sancretor** [comment]
Hi @rajainteq 

Thanks for your feedback !
Unfortunately, as stated in the project README, we are not compatible with SonarQube 8.6.
Please have a look at the dedicated section : https://github.com/cnescatlab/sonar-cnes-report#compatibility-matrix

**Comment by gvuspace** [comment]
Hi @rajainteq ,

I ran into the same exact problem. As a workaround, I applied the fix described [here](https://github.com/cnescatlab/sonar-cnes-report/issues/172#issuecomment-741729099) and rebuilt the plugin locally by running `mvn clean package`.

Looks like we'll have to resort to this method until an official binary supporting SonarQube 8.5+ is generated.

**Comment by rajainteq** [comment]
Hi @gvuspace,
Thanks for workaround fix, I have cloned the code locally to my system, but when I ran "**_mvn clean package_**" command its giving the below error, one test case is getting failed. Can you please help me to resolve this issue.
Please find the attached test case error log.

[fr.cnes.sonar.report.factory.ReportModelFactoryTest.txt](https://github.com/cnescatlab/sonar-cnes-report/files/5765633/fr.cnes.sonar.report.factory.ReportModelFactoryTest.txt)

**Comment by gvuspace** [comment]
Hi @rajainteq,

Do you have a SonarQube instance running on localhost:9001 on the machine you are using to build the plugin? If so, try to shut it down; alternatively, run "mvn clean package" on another machine (without any SonarQube instance running).

**Comment by rajainteq** [comment]
Hi @gvuspace,

You are awesome!!!
Thank you so much your workaround fixes its working now, able to generate reports from sonarqube 8.6.

Yes, I have followed your above steps, later I was able to build a jar file successfully.

Ton's of thanks! Great help! ...

**Comment by rajainteq** [comment]
> Hi @rajainteq ,
> 
> I ran into the same exact problem. As a workaround, I applied the fix described [here](https://github.com/cnescatlab/sonar-cnes-report/issues/172#issuecomment-741729099) and rebuilt the plugin locally by running `mvn clean package`.
> 
> Looks like we'll have to resort to this method until an official binary supporting SonarQube 8.5+ is generated.
> 
> EDIT: Somebody actually forked the repository and committed the workaround, you can clone directly from here: [KiYiul@0b8e218](https://github.com/KiYiul/sonar-cnes-report/commit/0b8e218f37329ff6939035e4600f1612ff34a536)

This workaround is working! Awesome help..

**Comment by gvuspace** [comment]
Hi @rajainteq 

Glad it worked :) However I must point out that @jeritiana and @KiYiul are the ones behind the original workaround, I only provided some extra guidance.

**Comment by kiingsec** [comment]
Solution confirmed to work on version 8.7 as well. Many thanks!
