### ISSUE TITLE
Command line option -v doesn't return version and pom version id & MANIFEST.MF still at 3.2.2

### ISSUE THREAD

**Issue by duffdiode** [cnescatlab/sonar-cnes-report#190]
running java -jar sonar-cnes-report-3.3.0.jar -v 
Results in:
[ERROR] Please provide a project with the -p argument, you can also use -h argument to display help.

Running with -v -p MyProject also results in Error
[ERROR] Illegal command line arguments

Furthermore, the version tag in META-INF/MANIFIEST.MF and in
META-INF/maven/fr.cnes.sonar/cnesreport/pom.xml
Shows 3.2.2

Binary artifact sha1sum is: 97493f995ba669bf686e08c323e51790f5e74ff3

**Comment by Sancretor** [comment]
Hi @duffdiode 

Thanks for your feedback !
We'll have a look at these two weird issues.

**Comment by duffdiode** [comment]
Confirmed that points raised have been resolved.
