### ISSUE TITLE
Date argument not working

### ISSUE THREAD

**Issue by nagmashaikh1** [cnescatlab/sonar-cnes-report#192]
#### Describe the bug

> When using sonar-cnes-report.jar as a standalone to create reports, the -d and --date both arguments are not working for passing date to create reports with date-filename.

#### To reproduce

> _Steps to reproduce the behavior._

1. I run java -jar sonar_report/sonar-cnes-report.jar -t token -s http://X.X.X.X:9000 -p projectname -b branch_name -o output_directory -d 2021-02-19
or
 java -jar sonar_report/sonar-cnes-report.jar -t token -s http://X.X.X.X:9000 -p projectname -b branch_name -o output_directory --date 2021-02-19
2. The reports generated don't take the value of date from the arguments list and generate report with current date only.

#### Expected behavior

> I expect report to be generated with the name date-filename with the date value being what I pass in -d or --date parameter

* OS: Linux

**Comment by Sancretor** [comment]
Hi @nagmashaikh1 

Thanks for your feedback !
We'll look into it as soon as possible.
