### ISSUE TITLE
More Code Coverage Details?

### ISSUE THREAD

**Issue by zekefromde** [cnescatlab/sonar-cnes-report#194]
Excellent plugin, THX.

Is there an easy way to expand the Code Coverage Results to be more than a total?

Quality Gate | Reliability | Security | Maintainability | Coverage | Duplications
:---:|:---:|:---:|:---:|:---:|:---:
OK | D | B | A | 61.0 % | 4.4 %

Like down the code tree to other levels of granularity?

Thx, keep up the excellent work.

**Comment by Sancretor** [comment]
Hi @zekefromde 

Thanks for your feedback, we truly appreciate it !
Right now, there is no easy way to show more details regarding coverage.
Depending on your project size, the tree could be huge and not fit smoothly inside a Word document...
That kind of precise details are usually put inside the Excel/CSV output.

What do you have in mind exactly ?

**Comment by Sancretor** [comment]
Without an answer to our question, we can't make any progress regarding this issue.
We're closing it for now, but feel free to reopen it if you have some feedback !
