### ISSUE TITLE
Unable to generate sonar (bitegarden/report api)report throws {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]} 

### ISSUE THREAD

**Issue by learnicode** [cnescatlab/sonar-cnes-report#196]
#### Describe the bug

> _A clear and concise description of what the bug is._

#### To reproduce

> _Steps to reproduce the behavior._

1. did sonar scan with vs code IDE
2. Go to Sonar server, click on Report
3. see error:- {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

#### Expected behavior

> It should generate a PDF report of the issues.

#### Screenshots & log

> _If applicable, add screenshots and logs to help explain your problem._ **Do not forget to obfuscate them if they contain sensitive data.**.

#### User environment 

> _Please complete the following information._

* OS: -. Windows 10
* sonar server version 8.6

**Comment by Sancretor** [comment]
Hi @learnicode 

Thanks for your feedback.
Unfortunately, as written in the README, we are not compatible with SonarQube 8.6.
We have plans for full compatibility with the next 8.x LTS version though.

**Comment by learnicode** [comment]
Hi @Sancretor 
Thank you for acknowledgement.
I will try scanning again with SonarQube other version and verify. Can u please specify which version of SonarQube is good to go with bitegarden api.

**Comment by Sancretor** [comment]
Hi @learnicode 
I absolutely don't know which SonarQube version may run with Bitegarden API...
I can only tell which SonarQube version our plugin is compatible with.
