### ISSUE TITLE
Report doesn't show security hotspot items

### ISSUE THREAD

**Issue by lupppo** [cnescatlab/sonar-cnes-report#197]
When I generate a report from my project, I realized that the security hotspot item are not shown in the report. 
![iamge](https://user-images.githubusercontent.com/5642109/110113272-2c40e300-7db3-11eb-8510-35b1140057fd.png)

Maybe is it correct because "securiy hotspot" doesn't have the severity categories. Just in case, it is confused.

**Comment by Sancretor** [comment]
Hi @lupppo 

Thanks for your feedback.
As far as I know, the security hotspots are only reported by the plugin on SonarQube 7.9 LTS right now.
For this SonarQube 8.x compatibility, we would have to break many things inside our codebase... (API changes)
So our simple strategy is to wait for the 8.x LTS to be released, and then provide a full compatibility with SonarQube 8.
