### ISSUE TITLE
[SQ 8.8] Generation of the report impossible in plugin mode because of wrong token

### ISSUE THREAD

**Issue by ErwanGauduchon** [cnescatlab/sonar-cnes-report#210]
#### Describe the bug

In plugin mode, an error appears when trying to generate the report.

#### To reproduce

1. Go to CNES report page
2. Click on Generate
3. The window shows error : "This project can't be exported, please check your token."

#### Expected behavior
The token used to generate the report should be a valid token.

#### User environment 

* OS: CentOS 7.8
* Project version: 3.3.1

**Comment by idjemaoune** [comment]
This version https://github.com/idjemaoune/sonar-cnes-report-1/releases/tag/3.3.2 works on 8.7.1

**Comment by Sancretor** [comment]
Seemed to be related to #172 which is now fixed on dev branch.

**Comment by HeWeiGitHub** [comment]
in plugin model ，sonarqube8.8 could`t start，Message ：
![image](https://user-images.githubusercontent.com/25758090/148742988-88cbf29a-c92a-4956-800d-09862a248e1c.png)

**Comment by HeWeiGitHub** [comment]
sonarqube8.8 & cnes-report3.X do export tips：
{"error":"This project can't be exported, please check your token."}

**Comment by Sancretor** [comment]
Hi @HeWeiGitHub 
This issue is closed so it may not be the best spot to get an answer.
Then, CNES Report 3.X is not compatible with SonarQube 8.8 as stated in the README.
Please do read the compatiblity matrix inside README : https://github.com/cnescatlab/sonar-cnes-report#compatibility-matrix
