### ISSUE TITLE
Unable to generate CNES Report for multiple projects

### ISSUE THREAD

**Issue by Nikhilnick1203** [cnescatlab/sonar-cnes-report#255]
####Unable to generate the CNES Report only for a couple of projects, it is working with other projects.

> Error: {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

#### To reproduce

> _Steps to reproduce the behavior._

1. Go to 'More'
2. Click on 'CNES Report'
3. Select a Project from the drop-down to'
4. See an error

#### Expected behavior

> It should download report analysis without any error

#### Screenshots & log

>![image](https://user-images.githubusercontent.com/71391042/119942448-7818b800-bfaf-11eb-9739-0f2133833a8a.png)

#### User environment 

> _Please complete the following information._

* Sonarqube Version: Community EditionVersion 8.1
* CNES Report version: 3.2.2

**Comment by ErwanGauduchon** [comment]
Hi @Nikhilnick1203, thank you for you feedback !

I see you are using version 3.2.2 of CNES Report, I suggest you to install version 3.3.1 which is available on marketplace (or in the releases of this repository). It fixes some bugs of the previous versions so maybe it will solve your problem.

Moreover, you are executing the CNES Report on a 8.1 SonarQube server while we don't ensure support for SonarQube versions > 7.9 LTS which can be a reason of your problem (although there are few changes between 7.9 LTS and 8.1). For information, we are currently developping a new version of CNES Report compatible with SonarQube 8.9 LTS, it will be released soon.

Finally, we can try to look at you problem anyway. Is there any specific configuration / plugin related to the projects with which CNES Report doesn't work (for instance a special character in a project name can lead to that type of bug) ? It would also be useful if you can provide us the logs of you SonarQube server.

**Comment by Sancretor** [comment]
Hi @Nikhilnick1203 
Do you have any update on this issue regarding @ErwanGauduchon's questions ?

**Comment by Sancretor** [comment]
Without any answer, we close this issue.
