### ISSUE TITLE
SonarQube 8.9: Sonar-CNES-Report Compatibility

### ISSUE THREAD

**Issue by MacDub757** [cnescatlab/sonar-cnes-report#258]
Is the software compatible with SonarQube 8.9? When I try to use the CLI I get the error GET_ISSUES_REQUEST = %s/api/issues/search?projects=%s&facets=types,rules,severities,directories,files,tags&ps=%d&p=%d&additionalFields=rules,comments&resolved=%s&branch=%s

When I try to use the GUI I get "This project can't be exported, please check your token."

Thank you

**Comment by Sancretor** [comment]
Hi @MacDub757 

For compatibility, just have a look at the README of the project, everything is clearly stated.
Here : https://github.com/cnescatlab/sonar-cnes-report#compatibility-matrix 
As of now, the project is not compatible with SQ 8.9.

But if you want to test our future release which will be compatible with SQ 8.9, you could build the "dev" branch.
Be aware that is still a work in progress that may not work yet, we won't provide any support until the next release.

**Comment by MacDub757** [comment]
> Hi @MacDub757
> 
> For compatibility, just have a look at the README of the project, everything is clearly stated.
> Here : https://github.com/cnescatlab/sonar-cnes-report#compatibility-matrix
> As of now, the project is not compatible with SQ 8.9.
> 
> But if you want to test our future release which will be compatible with SQ 8.9, you could build the "dev" branch.
> Be aware that is still a work in progress that may not work yet, we won't provide any support until the next release.

Thank you, in terms of setting up the plugin would I put the entire branch in the plugin folder? There isn't a Jar File in this branch. Which file do I use to execute the plugin? Thank you, Again.

**Comment by Sancretor** [comment]
@MacDub757 
The dev branch only contains raw code so it won't work as it is.
You need to compile the code to generate the plugin JAR file.
A simple `mvn clean package` would do the trick, just be sure to do this at the root the `dev` branch.

**Comment by MacDub757** [comment]
> @MacDub757
> The dev branch only contains raw code so it won't work as it is.
> You need to compile the code to generate the plugin JAR file.
> A simple `mvn clean package` would do the trick, just be sure to do this at the root the `dev` branch.

Gotcha, so I can compile the code from the root directory which has the package.json file?

**Comment by Sancretor** [comment]
Well... if you want to compile Java code with Maven, it's rather `pom.xml` you should be looking for.
But yes, you're right.

**Comment by MacDub757** [comment]
I will probably wait for the released version. Whenever I try to build the code out the jar file isn't generated.

**Comment by MacDub757** [comment]
Thanks for your help

**Comment by Sancretor** [comment]
A simple `mvn clean package` creates the JAR file inside a target directory, we do this multiple times a day without any problem.
You can close this issue as you wish.
