### ISSUE TITLE
Compile from source

### ISSUE THREAD

**Issue by richardcurteis** [cnescatlab/sonar-cnes-report#268]
Are there any instructions for compiling from source?

**Comment by Sancretor** [comment]
Hi @richardcurteis 
A simple `mvn clean package` at the root of the project is enough to compile it.
We will add this in the README for the next release, thanks for the feedback !

**Comment by richardcurteis** [comment]
Thanks, @Sancretor . Appreciate it.

**Comment by HeWeiGitHub** [comment]
CNES Report 4.0.0 not working for 8.8.0 in sonaqube server

**Comment by HeWeiGitHub** [comment]
CNES Report 4.0.0 not working for 8.8.0 in sonaqube server，windows 10
