### ISSUE TITLE
[ERROR] SonarQube instance is not supported by cnesreport.

### ISSUE THREAD

**Issue by Benthediver99** [cnescatlab/sonar-cnes-report#289]
I'm running Sonar.bat from zip file configuration.  I tried to use the plugin and got the error "{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}"
,so then I tried it from command line:

`java -jar sonar-cnes-report-4.0.0.jar -t [some_token_here] -a [Some_name_of_author] "C:\Users\_User_\Documents\SAST Benchmarking" -p Juliet-Test-CSharp-5
SonarQube URL: http://localhost:9000
SonarQube online: true
Detected SonarQube version: 9.1.0
[ERROR] SonarQube instance is not supported by cnesreport.`

Log files had this:
`Nov 03, 2021 7:44:12 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube URL: http://localhost:9000
Nov 03, 2021 7:44:13 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube online: true
Nov 03, 2021 7:44:13 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: Detected SonarQube version: 9.1.0
Nov 03, 2021 7:44:13 PM fr.cnes.sonar.report.ReportCommandLine main
SEVERE: SonarQube instance is not supported by cnesreport.
fr.cnes.sonar.report.exceptions.SonarQubeException: SonarQube instance is not supported by cnesreport.
	at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:140)
	at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:82)
`

**Comment by Benthediver99** [comment]
I notice in the code it checks the token, project, and url. Is it possible my token is in the wrong format?  Do I need the token name too?

**Comment by Benthediver99** [comment]
But then that wouldn't explain the plugin not working.

**Comment by Benthediver99** [comment]
I'm also using "sonarqube-9.1.0.47736"

**Comment by Sancretor** [comment]
Hi @Benthediver99 

The following line from your logs explains everything : 
`Detected SonarQube version: 9.1.0 [ERROR] SonarQube instance is not supported by cnesreport.`
The tool is simply not compatible with SonarQube 9.x, as stated in the README (https://github.com/cnescatlab/sonar-cnes-report#compatibility-matrix), so that's why it does not work.
It won't be compatible until the release of the next LTS version of SonarQube, for which we intend to release a new version of the CNES Report.

**Comment by Sancretor** [comment]
Hi @tarrinho 
As we're doing this during our free time, we decided to only work on LTS versions of SonarQube for compatibility.
SQ APIs may change a lot between 9.0 and 9.X LTS, and we rely a lot on them so... might be too much work to produce a new release every 3 months.
If you'd like to contribute, we'll gladly have a look at your PRs !
