### ISSUE TITLE
CNES REPORT 4.0.0 -- Charts are not getting generated.

### ISSUE THREAD

**Issue by inugravi** [cnescatlab/sonar-cnes-report#293]
Hello Team,

I was using sonarqube 8.9.2 version. So I have been using the cnes report flawlessly. After upgrading to 8.9.6.50800 last night., when tried downloading the report, it is downloading the report but Charts are failing to reflect on the downloaded attachment. 
(Please find the attached pic for reference)

I need your help in making the plugin compatible to version 8.9.6.50800.

Note: 1. I have been using the sonar-cnes-report 4.0.0
          2. I have compiled the plugin with **`mvn package`**  command by changing the **`<sonar.apiVersion>`** to 8.9.6.50800 in pom.xml
   
![noch](https://user-images.githubusercontent.com/81733572/147256529-cc77c16b-48eb-44da-a85c-85f748c95b17.PNG)

**Comment by Sancretor** [comment]
Hi @inugravi 
Thanks for the feedback, and sorry for this issue.
We'll have a look at this as soon as possible, but it looks like a compatibility issue... which is weird on a minor update.

**Comment by inugravi** [comment]
HI @Sancretor, 
<my savior>

Thanks for acknowledging. I will be waiting for your response.

**Comment by inugravi** [comment]
Hi @Sancretor ,

Yes, I have downloaded the same project for earlier version SQ 8.9.2 as well. After upgrading to minor version 8.9.6.50800 
I'm facing this error for the same project. 

Can you please build the plugin for me in one of the branches /or on new branch and give it to me. 
(For me also the log file looks fine)

**Comment by Sancretor** [comment]
Hi @inugravi 
There's no need to re-build this plugin for SQ 8.9.6, it already works for each 8.9.x versions.
I can't reproduce your error, and you don't have any logs from SonarQube, so I'm afraid I can't do much.

As I said before, this might be a Word rendering bug...
Did you try the lazy workaround I gave previously ?

**Comment by inugravi** [comment]
Hi @Sancretor ,

I can share the logs with you but which logs should i share from the below list
![image](https://user-images.githubusercontent.com/81733572/148747024-30e9d03e-bcf5-4907-9d20-32989b365ae5.png)

And BTW the lazy workaround which u told .. I could not get it.. any hints on it ?

**Comment by Sancretor** [comment]
Hi @inugravi 
Regarding the "workaround"... I sometimes have a weird bug like you where Word doesn't show any chart.
Just by clicking or double-clicking on the empty chart, Word usally makes it appear "magically".
A rendering bug I guess...

If you don't see any ERROR/WARNING in any of those logs, then there is nothing useful to find in them.

**Comment by inugravi** [comment]
ok. Noted @Sancretor I will test it and will let u know.

**Comment by inugravi** [comment]
Hello @Sancretor ,
Still the same issue. Anyways I will try to use the upgraded plugin 4.1.0 and will let u know

**Comment by Sancretor** [comment]
Hi @inugravi 
Just to let you know that we release a fix version (4.1.1) that resolves a Word format issue with the generated charts.
Could you give it a try, please ?

**Comment by inugravi** [comment]
Hi @Sancretor 

Thanks a million for the good news. I will try with the latest version 4.1.1 and will let you know the status.

**Comment by Sancretor** [comment]
Hi @inugravi 
Do you have good news regarding your test ?

**Comment by inugravi** [comment]
Dear @Sancretor 

We have tested this new version 4.1.1 and we are very much delighted to inform that this is working like a charm.

Lots of love from India.

**Comment by Sancretor** [comment]
Good news then ! You're welcome.
