### ISSUE TITLE
Not able to generate report on sonarqube 9.2.1

### ISSUE THREAD

**Issue by pmmanav** [cnescatlab/sonar-cnes-report#294]
#### Describe the bug
When trying to generate the report. I am getting following error.

{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

And in command prompt I am getting response  is that, detected sonarqube version 9.2.1

jvm 1    | INFO: SonarQube URL: http://localhost:9000                                                                   jvm 1    | Jan 04, 2022 2:27:51 PM fr.cnes.sonar.report.ReportCommandLine execute                                       jvm 1    | INFO: SonarQube online: true                                                                                 jvm 1    | Jan 04, 2022 2:27:51 PM fr.cnes.sonar.report.ReportCommandLine execute                                       jvm 1    | INFO: Detected SonarQube version: 9.2.1

**Comment by Sancretor** [comment]
Hi @pmmanav 
As discussed previously in this issue #270, and clearly stated inside the README, the plugin is not currently compatible with SonarQube 9.x versions.
We'd like to wait for the next stable release to update the plugin.
