### ISSUE TITLE
Error with sonar SNAPSHOT version for example '8.9.1-SNAPSHOT'

### ISSUE THREAD

**Issue by zorikmostly** [cnescatlab/sonar-cnes-report#297]
Application is not working when sonarqube version is SNAPSHOT. The issue is coming from 

   this.versionRevision = Integer.parseInt(numbers[2]);

    public void setVersion(final String pVersion, final boolean pSupported) {
        final String[] numbers = pVersion.split("\\.");
        // case when version is X.Y
        if(numbers.length >= 2) {
            this.versionMajor = Integer.parseInt(numbers[0]);
            this.versionMinor = Integer.parseInt(numbers[1]);
            // case when version is X.Y.Z
            if(numbers.length >= 3) {
                this.versionRevision = Integer.parseInt(numbers[2]);
                // case when version is X.Y.Z.build
                if(numbers.length >= 4) {
                    this.versionBuild = Integer.parseInt(numbers[3]);
                }
            }
        }
        this.supported = pSupported;
    }

**Comment by Sancretor** [comment]
Hi @zorikmostly 
Thanks for your feedback, and sorry for this issue.
We'll look into it as soon as possible.

**Comment by Sancretor** [comment]
Hi @zorikmostly 
As I was working on this issue, I was not able to find any SonarQube release in SNAPSHOT.
Could you please tell me where you found yours ?
It'll help me make sure the fix will work in real conditions.

**Comment by zorikzaqaryan** [comment]
This is the link for sonarqube 
https://github.com/SonarSource/sonarqube/archive/refs/tags/8.9.1.44547.tar.gz

I just downloaded it, unzip and run ./start.sh 
I checked version in 
http://localhost:9000/api/system/status 
and got something like this 
 
 {
id: "BF41A1F2-AX5xg_BeK-H7vXvCIKmF",
version: "8.9.1-SNAPSHOT",
status: "UP"
}

**Comment by Sancretor** [comment]
Hi @zorikzaqaryan 
For the sake of simplicity, we changed the way the version was handled so this issue won't happen again.
The fix is merged in the dev branch and a new release may come soon.
Thanks for your feedback !

**Comment by zorikzaqaryan** [comment]
> Hi @zorikzaqaryan For the sake of simplicity, we changed the way the version was handled so this issue won't happen again. The fix is merged in the dev branch and a new release may come soon. Thanks for your feedback !

@Sancretor Thank you
