### ISSUE TITLE
sonar-cnes-report 4.0 plugin doesn't support SoanrQube 9.3

### ISSUE THREAD

**Issue by khopithan** [cnescatlab/sonar-cnes-report#305]
Hi all

I tried to add sonar-cnes-report plugin 4.0 into SonarQube server 9.3 but I was not able to generate reports and got to know about that this plugin supports only SoanrQube 8.9 and 8.9.* versions.

So, I try to build the code by myself by adding the versions into [HOME]\sonar-cnes-report-master\src\main\java\fr\cnes\sonar\report\factory\ServerFactory.java file but when I open the code in eclipse IDE, there are some errors that I don't understand. I hope that you will add this feature in your future release.

Regards,
Khopi

**Comment by firmianay** [comment]
mark

**Comment by Sancretor** [comment]
Hi @khopithan 

Thanks for your feedback !
The exception that prevents the plugin from working on non compatible SonarQube versions will be removed in the next release (4.1.0).
But, again, SonarQube 9.x won't be supported until the release of the next SQ 9.x LTS version. 
We are working on this tool during our free time, so we only work on LTS releases to same some !

See #270
