### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by TheRealAyCe** [cnescatlab/sonar-cnes-report#307]
#### Describe the bug

Console:

```
...
SonarQube URL: http://localhost:9000
SonarQube online: true
Detected SonarQube version: 8.9.7
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.openxml4j.util.ZipSecureFil
e$1 (file:/G:/Sonarqube/sonar-cnes-report-4.0.0.jar) to field java.io.FilterInpu
tStream.in
WARNING: Please consider reporting this to the maintainers of org.apache.poi.ope
nxml4j.util.ZipSecureFile$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect
ive access operations
WARNING: All illegal access operations will be denied in a future release
Report generation: SUCCESS
```

#### To reproduce

I just analyzed my project:
java -jar sonar-cnes-report-4.0.0.jar -t mytoken -p myproject

#### User environment 

* OS: Windows 7
* Project version: 4.0.0

```
C:\Users\AyCe>java -version
java version "15" 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)
```

**Comment by Sancretor** [comment]
Hi @TheRealAyCe 

Thanks for the feedback !
We are aware of these warnings but still haven't investigate much yet.

Just to be sure, your issue only deals with these warnings, right ?
You do not encounter any wrong behaviour ?

**Comment by TheRealAyCe** [comment]
It says "report generation: success", and the report seems fine. So no other issues I think.

**Comment by Sancretor** [comment]
Thanks !
We will try to fix this for a future release, it may take a while, I can't any promise.
