### ISSUE TITLE
Sonarqube 8.7 support

### ISSUE THREAD

**Issue by evasokolova1f** [cnescatlab/sonar-cnes-report#308]
Hi!

I'm using SonarQube 8.7. Is there plugin support for this version?

**Comment by evasokolova1f** [comment]
In docs if found:
`In plugin mode, copy jar in /opt/sonarqube/extensions/plugins, restart sonarqube, then click on "More" > "CNES Report".`
I do it. But can't find "More" button in Web UI. Can you help me, please?

**Comment by un0tec** [comment]
Hi @evasokolova1f,

You can see the versions compatible with the plugin [here](https://github.com/cnescatlab/sonar-cnes-report/blob/master/README.md#compatibility-matrix) and [here for legacy versions](https://github.com/cnescatlab/sonar-cnes-report/wiki#note-on-legacy-versions).

They have recently released the [version 4.1.0](https://github.com/cnescatlab/sonar-cnes-report/releases/tag/4.1.0), which allows to enable experimental use for unsupported versions.

Regards.

**Comment by evasokolova1f** [comment]
Hi @un0tec,

I tried to install 4.1.0 version. And get such error in web.log:
`2022.02.28 10:49:51 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed: Plugin SonarQube CNES Report [cnesreport] requires at least SonarQube 8.9.0.43852`.

Are there another options to install plugin?

Best regards,
Eva Sokolova

**Comment by un0tec** [comment]
Hi @evasokolova1f,

The plugin is only officially supported for LTS version as you can see [here](https://github.com/cnescatlab/sonar-cnes-report/blob/master/README.md#compatibility-matrix). If trying version 3.3.x or 4.x didn't work for you.

Perhaps one of the plugin's proprietary developers can give you some further direction.

Anyway, if you are currently using version 8.7 I recommend you to upgrade your SonarQube instance to version 8.9 LTS, it should be easy.

Regards.

**Comment by evasokolova1f** [comment]
Hi @un0tec,

I updated to 8.9 and successfully installed plugin. Thank you!

Best regards,
Eva Sokolova
