### ISSUE TITLE
Error while generating report -  {"errors":[{"msg":"For input string: \"_AFourReports.cshtml\""}]}

### ISSUE THREAD

**Issue by AbhijitKhillari** [cnescatlab/sonar-cnes-report#312]
#### Describe the bug

> _A clear and concise description of what the bug is._

I'm running a report for a project with Dot Net Framework 4.6.1.
While generating report it is showing error "{"errors":[{"msg":"For input string: \"_AFourReports.cshtml\""}]}"
_AFourReports.cshtml is file in the project.
 
SonarQube version - 8.9 LTS
CNES report version - 4.0

#### To reproduce

> _Steps to reproduce the behavior._

1. Go to 'More'
2. Click on 'CNES Report'
3. Fill in the required data
4. Click on Generate button

#### Expected behavior

> Report Should be generated

#### Screenshots & log

> 
![image](https://user-images.githubusercontent.com/13469378/157813010-d3b1a764-575b-44c8-a647-5f18d5f35bd6.png)
![image](https://user-images.githubusercontent.com/13469378/157813133-9a18e5bf-ccd1-4689-9618-2a16c73b862e.png)

#### User environment 

> _Please complete the following information._

* OS: [e.g. Windows 10]
* .NET framenwork 4.6.1
* SonarQube 8.9 LTS
* CNES Report 4.0

**Comment by Sancretor** [comment]
Hi  @AbhijitKhillari 
Sorry for the huge response time... but thanks for the feedback !
With these elements, I can't tell exactly what the problem was, but I would bet it's the filename (beginning with an underscore).
Could you try to rename it just to check that, please ?
Otherwise, I would need some SonarQube **server** logs to debug this precisely...

**Comment by Sancretor** [comment]
Hi @AbhijitKhillari 
I haven't been able to reproduce your error with plugin version 4.1.1 on SonarQube 8.9.8.
I don't know if the latest of our releases fixes the problem, or if I just don't have enough data to full reproduce your situation....

Could you please provide some SonarQube **server** logs as requested previously ?
Don't forget to remove sensitive data.

**Comment by Topin2001** [comment]
Without any news, I close this old issue.
If anything similar happens again, we'll re-open it.
