### ISSUE TITLE
How are Security Hotspot Category keys acquired?

### ISSUE THREAD

**Issue by Meizikyn** [cnescatlab/sonar-cnes-report#314]
Our team needs to use sonar-cnes-report with SonarQube 9.3; we have taken to fixing the compatibility issues ourselves. So far, the only breaks in compatibility we can find are that SonarQube has new "Security Hotspot Categories" that sonar-cnes-report cannot parse. 

We've narrowed down the means of adding support for these missing categories in `main.java.fr.cnes.sonar.report.utils.StringManager SECURITY_HOTSPOT_CATEGORIES. It seems to ensure that new categories are shown in reports, we need only provide their internal key and map it to a descriptive title to be shown in the reports.

However, we cannot locate where in the SonarQube source code that we can find the origin of these category keys. Our assumption is that sonar-cnes-report recieves data from SonarQube that contains a list of category keys that apply to that specific project.

Thus our question is this: Where are you acquiring the security hotspot category keys from? Are they provided directly from SonarQube? If not, how are you acquiring them? We're looking for the specification that will provide ALL new category keys for the latest SonarQube to bridge the compatibility gap.

**Comment by Sancretor** [comment]
Hi @Meizikyn 

Sorry for the huge delay... and thanks for sharing the fixes you had to deal with ! :)
We'd be happy to study your contribution.

Regarding the Security Hotspots key, I don't remember exactly how we found them...
We're not retrieving them dynamically, I guess it was somewhere in the documentation or SQ source code.
Anyway, in the SonarQube web interface, you can get them from the "Rules" page.
Open the "Security Category" filter, and you will find all the various category.
While applying one of these filter, the URL will change and you'll find the ID of the category in a dedicated parameter, like `owaspTop10=a6` or `cwe=200`, and so on.
Not very practical, but it'll do the job...

Does it solve your issue ..?

**Comment by flyingcircle** [comment]
We added:
```java
SECURITY_HOTSPOT_CATEGORIES.put("permission", "Permission");
SECURITY_HOTSPOT_CATEGORIES.put("encrypt-data", "Encryption of Sensitive Data");
SECURITY_HOTSPOT_CATEGORIES.put("traceability", "Traceability");
```
In `StringManager.initSecurityHotspotsCategories`

And that got it working.

**Comment by flyingcircle** [comment]
^Could probably add it safely to the plugin today without breaking any previous version compatibility.

**Comment by Sancretor** [comment]
Hi @flyingcircle 

Thanks for the fix ! :)
I'll do some tests to ensure it won't break previous SQ compatibility.

Maybe you'd like to open a Pull Request yourself ?
So that your contribution would be publicly registered...

**Comment by flyingcircle** [comment]
@Sancretor done. I hit a couple of unit test errors: 
```
[ERROR] Failures: 
[ERROR]   AbstractFacetsProviderTest.getTimeFacets:143 expected:<44419.59709490741> but was:<44419.22209490741>
[ERROR]   DateConverterTest.validSonarQubeDateToExcelDateTest:15 expected: <44419.50796296296> but was: <44419.2162962963>
```
But these look like timing errors unrelated to my changes.

I wasn't sure how to run the linter, but I think my code would pass.

**Comment by Sancretor** [comment]
Don't worry about those errors...
We don't know how to manage SonarCloud analysis for external PRs, and timing errors sometimes appear for some reason.

Thanks a lot for your contribution, it's highly appreciated ! :)
