### ISSUE TITLE
Missing issue information for external analyzers

### ISSUE THREAD

**Issue by christopher-watanabe-snkeos** [cnescatlab/sonar-cnes-report#317]
#### Describe what you need to know

I am using the Sonar CNES report tool v4.1.1 with SonarQube Community Edition 8.9.8. What I've noticed is that SonarSource errors are generated with name, description, type, severity and number information. External Roslyn analyzer issues are however only shown with the name (i.e. "external_roslyn:CA1051") and number information. Other fields are given "?", as if the information were missing. The "?" labelled fields are available on the SonarQube server however, so I expect this information is not truly missing (see screenshots). 

I'd like to know whether I'm configuring my report generation wrong or whether this is a feature that is not yet supported, namely importing of external analyzer issues in the report with full information.

#### Screenshots & log

"?"-labelled content in the report 
![image](https://user-images.githubusercontent.com/91735518/168762151-32f6b02b-017c-4fa8-87e8-79b80be194f9.png)

Information given in SonarQube with the same external error code (circled red)
![image](https://user-images.githubusercontent.com/91735518/168762560-e3875b43-853d-4408-96f3-f83f496641cd.png)

#### User environment 

> _Please complete the following information._

* OS: Windows 10
* Project version: Release 4.1.1, SonarQube Community v.8.9.8

**Comment by Sancretor** [comment]
Hi @ChristopherWatanabe 
Thanks for the feedback ! ... and sorry for this issue.
Honestly, I would need to investigate a bit to answer correctly, but it may be an issue on our side, rather than a misconfiguration on yours.
I'll give you an update as soon as possible.

**Comment by ChristopherWatanabe** [comment]
Thank you @Sancretor ! In the meantime, it seems that quite a few of these external warnings (incorrectly mislabelled errors by me!) can be picked up by expanding the SonarQube C# Ruleset, which is perhaps why this is just now become an issue. For the greatest amount of analysis and peace of mind however, I would ultimately like to include external analyzer warnings and information as well. 

I hope your investigation is fruitful! Looking forward to your results!!!

**Comment by ChristopherWatanabe** [comment]
Hi @Sancretor, 

Just taking a short look around, I think the problem is [here](https://github.com/cnescatlab/sonar-cnes-report/blob/b86f8ea17c6915536af60cffa28472b171c0e421/src/main/java/fr/cnes/sonar/report/exporters/data/IssuesAdapter.java#L114). It seems if the rule is not listed in the Sonar ruleset - as is the case for all external rules - then it is assumed that the report doesn't include information about that rule, which is not always the case.

**Comment by christopher-watanabe-snkeos** [comment]
Hi @Sancretor 

No rush! I considered developing this processing to generate the unique list of issues with their number of occurrences myself, but I'm no Java expert and I don't have **that** much free time! 😄 My team also ended up considering a paid service that generates these sort of PDFs with SonarQube/SonarCloud output, especially if we take the SonarCloud route. Perhaps you've heard of it it? It's called [BiteGarden](https://www.bitegarden.com/). 

Thank you for your response! :)
