### ISSUE TITLE
Project Name Bug regarding the CNES Report

### ISSUE THREAD

**Issue by muhyid** [cnescatlab/sonar-cnes-report#319]
#### Describe the bug

It seems if the project name contains "**:**" there is a problem. 

My Environment:
Windows Server 2016
SonarQube 8.9.8 LTS Community Edition
Java 11.0.13 LTS

We are using the ProjectKey:1.0.0 format for Project Names. When I try to get a report from the project that is named like this. CNES report is running successfully and It says "Report generation: SUCCESS", But it is not producing any report file and occurring only 1 file with 0 bytes. 
If I change the Project name like the ProjectKey-1.0.0 format. It is running properly and producing all report files 
There is a log for problematic ProjectKey:1.0.0 format in the following. The result is exactly the same for the successful ones.
SonarQube URL: http://localhost:9000
SonarQube online: true
Detected SonarQube version: 8.9.8.54436
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.openxml4j.util.ZipSecureFile$1 (file:/C:/sonarqube/extensions/plugins/sonar-cnes-report-4.1.1.jar) to field java.io.FilterInputStream.in
WARNING: Please consider reporting this to the maintainers of org.apache.poi.openxml4j.util.ZipSecureFile$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Report generation: SUCCESS

#### To reproduce

> _Steps to reproduce the behavior._

1. Please create a project with **ABC-DEF:1.0.0** format
2. Please run CNES report
3. Check the zip file
4. Please create a project with **ABC-DEF-1.0.0** format
5. Please run CNES report
6. Check the zip file

**Comment by Sancretor** [comment]
Obviously, Windows does not accept ":" in filenames, and as we mostly work on Linux machines, we did not see this issue.
I'll make a fix for this, and it will be packaged inside the next version...
Unfortunately, I can't tell you exactly when it'll be released though.
