### ISSUE TITLE
Received 504 Gateway Timeout as plugin mode

### ISSUE THREAD

**Issue by mickey2012ex** [cnescatlab/sonar-cnes-report#321]
#### Describe the bug

When downloading report with large number of issue, it will received 504 Gateway Timeout (around 30 second) as plugin mode.
But i can download it using standalone mode.
Is there a option to increase the default timeout?

#### To reproduce

Generate report with around 100k issues and code smell project

#### Screenshots & log

![image](https://user-images.githubusercontent.com/9796231/172565125-d6366adc-1ae8-4db5-9db0-d106e3008985.png)

#### User environment 

Sonarqube 8.9.8 LTS - community version

**Comment by Sancretor** [comment]
Hi @mickey2012ex 
As far as I know, we don't have anything to configure the plugin page timeout.
It might also be a configuration inside the SonarQube server, or even your front proxy if there is one.
I'll try to investigate this on our side, but not sure we have a project with 100k issues to reproduce...

**Comment by Sancretor** [comment]
I managed to create a project with 200k issues, but the report was still generated successfully... maybe the server was powerful enough to compute before timeout.

**Comment by mickey2012ex** [comment]
Thanks for your help.
If I find the solution,I will post it here too.

**Comment by mickey2012ex** [comment]
I have solved the issue. Thanks for your suggestion.

My sonarqube is hosting on Openshift 4. 
By default, the OpenShift route is configured to time out HTTP requests that are longer than 30 seconds.

To increase this, add "haproxy.router.openshift.io/timeout: 60s" to the annotations of your Routes

**Comment by Sancretor** [comment]
Thanks for your feedback ! :)
