### ISSUE TITLE
Special Character Issue

### ISSUE THREAD

**Issue by Anis-Sayyad-Tavisca** [cnescatlab/sonar-cnes-report#336]
> _Before posting a new question, please read the README.md and check existing issues._

#### Describe what you need to know

I need to pass the project name\Key with "/"  and "@"special characters e.g. abc/@xyz/pqr, but I am getting the below error.
Does cnesreport is compatible with this special characters for project name\key?

#### Screenshots & log

![Capture](https://user-images.githubusercontent.com/115683915/200488597-6c3b8d65-ecc3-4bb5-bf65-af74c895417d.PNG)

#### User environment 

> _Please complete the following information._

* OS: Windows 10 
* Project version: 8.1.0

**Comment by louisjdmartin** [comment]
Hello,
Yes it was a bug, it's fixed in latest release
