### ISSUE TITLE
 Impossible to reach SonarQube instance while sonarqube is accessable

### ISSUE THREAD

**Issue by giannakopoulosj** [cnescatlab/sonar-cnes-report#342]
While the URL is accessible by curl, the jar reports the Sonarqube as down
Do we miss something?

#### Screenshots & log

![image](https://user-images.githubusercontent.com/2518387/207893025-06009b3d-047c-4cf6-9225-2eae7202638a.png)

* OS: WSL2 Ubuntu 22.04.1 LTS
* Project version: 4.1.3

**Comment by trimalcione** [comment]
Same here, with same configuration.
SQ version: Community - 9.8.0.63668
