### ISSUE TITLE
Sonarqube new LTS 9.9 support

### ISSUE THREAD

**Issue by theljade** [cnescatlab/sonar-cnes-report#345]
Hello, there is a new LTS version of sonarqube.

I'll try to take some time to help you to make the update, but I'm still creating the issue in order to trace it :)

**Comment by rcfja** [comment]
Not sure if this information helps but this plugin caused this issue for me : https://community.sonarsource.com/t/ui-is-showing-i18n-keys-and-not-english-text/85688
