### ISSUE TITLE
Unable to generate reports for few projects using CNES plugin

### ISSUE THREAD

**Issue by eshwarkarthikn** [cnescatlab/sonar-cnes-report#346]
We are using CNES 4.0.0 in Sonarqube 8.9 LTS version and we have more than 3k projects on the server. We are able to generate reports for most of the project but **getting proxy error** for few projects. 

Steps to reproduce the behavior.

1. Go to Sonarqube Dashboard
2. Click on More drop down menu and click CNES Report 
3. Select the Project, Branch key, Report Language and click Generate

#### Expected behavior

Once we click generate, it should download the report.

#### Screenshots & log

<img width="408" alt="Proxy Error" src="https://user-images.githubusercontent.com/125032966/218090717-5c74cb0a-b03a-4a78-890b-7cf7d1c49a22.PNG">

Note: We haven't observed any high utilization of resources in server while generating the report.

Please find the following information.

* OS: RHEL 7.9
* Sonarqube Version: 8.9.9 (build 56886)
* CNES Plugin version: 4.0.0

**Comment by eshwarkarthikn** [comment]
Hi,

any update on this issue?


Thank you!

**Comment by Topin2001** [comment]
Without any reponse, I'm closing this issue, feel free to ask me to re-open it if you encounter this issue again
