### ISSUE TITLE
[ERROR] Insufficient privileges error sent by SonarQube server (code 403)

### ISSUE THREAD

**Issue by tcsabina** [cnescatlab/sonar-cnes-report#351]
Hi!

We are running "Developer Edition Version 9.9 (build 65466)" of Sonarqube as a kubernetes pod. It was installed/configured based on the official documentation.

I am trying to use the sonar-cnes-report plugin on the command line, with the following script:
`java -jar sonar-cnes-report-4.1.3.jar -t <token> -s https://<sqserver.com> -p <projectID> -b <mybranch>`

It generates the following error:
`[ERROR] Insufficient privileges error sent by SonarQube server (code 403), please check your permissions in SonarQube configuration.`

If I use the plugin using the webUI of sonarqube (More->CNES report), it works fine. I am using the same users who's token is used in the command line...

There is not much visible in the sonarqube logs, so I would like to ask for help about how to debug this issue? Is there a way to increase the loglevel of the sonarqube instance and/or the plugin to see somehow what is actually wrong?
.cnesreport/log/cnesreport-0.log content:
`May 01, 2023 10:52:42 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube URL: https://<mysonarqube.server>
May 01, 2023 10:52:43 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube online: true
May 01, 2023 10:52:43 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: Detected SonarQube version: 9.9.0.65466
May 01, 2023 10:52:43 PM fr.cnes.sonar.report.ReportCommandLine main
SEVERE: Insufficient privileges error sent by SonarQube server (code 403), please check your permissions in SonarQube configuration.
fr.cnes.sonar.report.exceptions.BadSonarQubeRequestException: Insufficient privileges error sent by SonarQube server (code 403), please check your permissions in SonarQube configuration.
        at fr.cnes.sonar.report.providers.RequestManager.get(RequestManager.java:170)
        at fr.cnes.sonar.report.providers.AbstractDataProvider.stringRequest(AbstractDataProvider.java:325)
        at fr.cnes.sonar.report.providers.AbstractDataProvider.request(AbstractDataProvider.java:281)
        at fr.cnes.sonar.report.providers.project.ProjectProviderStandalone.getProjectAsJsonObject(ProjectProviderStandalone.java:60)
        at fr.cnes.sonar.report.providers.project.AbstractProjectProvider.hasProjectAbstract(AbstractProjectProvider.java:128)
        at fr.cnes.sonar.report.providers.project.ProjectProviderStandalone.hasProject(ProjectProviderStandalone.java:52)
        at fr.cnes.sonar.report.factory.ReportModelFactory.create(ReportModelFactory.java:101)
        at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:145)
        at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:82)
`

If I mistype the token, I get the message to use a valid token.
If I mistype the projectID, I get an error that there is no such project.
If I mistype the branchName, I get an error that there is no such branch in that project.
So the initial handshake seems to work fine.

I also know that there is no official release of the sonar-cnes-plugin for SQ 9.9. I have built it myself (based on [this PR](https://github.com/cnescatlab/sonar-cnes-report/pull/350).

Regards,
Tamas

**Comment by diegorodriguez31** [comment]
Dear @tcsabina , we will investigate on your issue soon. But first, we will release the PR you mentionned to at least have the plugin compatible with SonarQube9. In a second time, we will tackle your issue the sooner as we can.
Thank you for your comprehension.

**Comment by tcsabina** [comment]
Hi @diegorodriguez31 ,

Thanks for the reply.
Let me know if there is anything I can test/debug.

**Comment by tcsabina** [comment]
Hello @louisjdmartin ,m

Thanks! This was it.

I had a 'Global Analyses Token', which didn't work.
Using a 'User Token' works fine!

I've made a PR (https://github.com/cnescatlab/sonar-cnes-report/pull/353) to highlight a bit better in the Readme that we need a 'User token' ;).
