### ISSUE TITLE
CNES Fails to Generate Reports for Pull Requests in SonarQube

### ISSUE THREAD

**Issue by alexandrasims** [cnescatlab/sonar-cnes-report#356]
#### Describe the bug

When using the the Sonar CNES Report tool within our CI/CD pipeline, the report fails to generate after CNES attempts to fetch project data from the SonarQube server for a **Pull Request**.

After reviewing the sonar-cnes-report codebase, it appears that the tool has not yet implemented the ability to handle generating reports for Pull Requests in SonarQube?

As a result, our users are not able to generate CNES reports for their projects during Pull Request builds. This is causing disruptions for them during their normal development workflow.

#### To reproduce

> _Steps to reproduce the behavior._

1. Version control system is configured to trigger a project build in CI/CD tool for a newly opened Pull Request (which includes a sonar scan and CNES report generation).

2. **The sonar scan results for the PR are successfully pushed to the SonarQube server by the sonar scanner from the CI/CD tool; however, the Sonar CNES Report tool fails to run due to not being able to find the project branch name within SonarQube.**

I believe this is because the CNES tool only uses the internal SonarQube API call, `GET api/navigation/component` with the `branch` parameter to retrieve project data, instead of also accounting for project branches that need to be called with the `pullRequest `parameter.

It also seems like SonarQube is only expecting the PR **number** from the pull request name for the parameter value:
`https://<sonarqubeserver>/dashboard?id=project-name&pullRequest=412`

#### Expected behavior

Expected behavior is for the Sonar CNES Report tool to be able to successfully make a call to a Pull Request on a SonarQube server.

#### Screenshots & log
<img width="1026" alt="image" src="https://github.com/cnescatlab/sonar-cnes-report/assets/42222840/43ab90e3-038d-4b82-bfeb-04be82da1a31">
<img width="1410" alt="image" src="https://github.com/cnescatlab/sonar-cnes-report/assets/42222840/87fbc36f-1b17-4bac-81b0-fd6d0869fa2d">

#### User environment 

* Project version: 4.1.3
* SonarQube Server version: 9.9.0.65466

**Comment by bientt210** [comment]
Sonarqube 9.9 support from version 4.2.0, you may need to update to version 4.2.0.

**Comment by Topin2001** [comment]
Without any news since last year, I'm closing this issue, feel free to re-open it if needed
