### ISSUE TITLE
Sonarqube 9.7.1 translations missing after install of sonar-cnes-report-4.1.3.jar

### ISSUE THREAD

**Issue by jbourdellon** [cnescatlab/sonar-cnes-report#357]
#### Describe the bug

On multiple pages in the translations are missing after installing the plugin.
These translations are correct before the installation of the plugin of after uninstalling the plugin.

#### To reproduce

> _Steps to reproduce the behavior._

[Go to '...'](https://{$SONAR_URL}/projects?sort=analysis_date)

![image](https://github.com/cnescatlab/sonar-cnes-report/assets/5785689/7c0c2877-5e92-460e-ab82-6cf7b4afbe0e)

#### Expected behavior
Translations remain correct

![image](https://github.com/cnescatlab/sonar-cnes-report/assets/5785689/02d4660b-ddb2-41dc-9a1d-b11399056ffe)

#### Screenshots & log

> _If applicable, add screenshots and logs to help explain your problem._ **Do not forget to obfuscate them if they contain sensitive data.**.

#### User environment 

    Sonarqube Community Edition Version 9.7.1 (build 62043
    sonar-cnes-report-4.1.3.jar
    Official docker image :  sonarqube:9.7.1-community

**Comment by Topin2001** [comment]
Hello, thanks for the interest, however, we only support the LTS version, and it's currently the 9.9.3.
