### ISSUE TITLE
Availability of CNES for SonarQube 10.x version

### ISSUE THREAD

**Issue by gowthamc206** [cnescatlab/sonar-cnes-report#358]
Hi Team,
Greetings of the day.
We are using SonarQube latest version 10.x. May I know when the CNES report is available for the SonarQube version 10.x.
Thank you in advance...

Thanks and Regards
Gowtham Chendra

**Comment by dermooods** [comment]
+ 1

**Comment by johnfelipe** [comment]
{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

i have this error when using latest version of sonar

**Comment by johnfelipe** [comment]
When will have compatibility with latest version of sonarqube?

**Comment by buzz3791** [comment]
I was able to get a private build of cnesreport 4.2.x to work on SonarQube 10.2.1 without too much trouble.
Details are here:
https://github.com/cnescatlab/sonar-cnes-report/issues/361#issuecomment-1811313352

**Comment by Topin2001** [comment]
Hello, thanks for the interest, however, we only support the LTS version, which is currently not available for the v10.
