### ISSUE TITLE
CNES 4.2 fails to display project options in SonarQube LTS 9.9.1

### ISSUE THREAD

**Issue by riccab** [cnescatlab/sonar-cnes-report#362]
#### Describe the bug

When attempting to generate a report from the UI, More > CNES Report, we are not getting a list of projects to select from even though several projects with analysis exist and user has access to.

#### To reproduce

1. Add sonar-cnes-report-4.2.0.jar to /opt/sonarqube/extensions/plugins
2. Set permissions to 0704 so other has read permissions
3. Restart SonarQube LTS 9.9.1-enterprise docker container
4. Navigate to web interface > More > CNES Report
5. Select drop-down for 'Projects'
6. Note 'Projects' list is empty

#### Expected behavior

Expect list of Projects to display in 'Projects' list

#### Screenshots & log
Error from sonarqubeurl/api/cnesreport/report: {"errors":[{"msg":"The \u0027key\u0027 parameter is missing"}]}
Log error from sonarqube docker logs output: [o.s.u.c.UpdateCenter] The plugin 'cnesreport' version : 4.2.0 has not been found on the update center.

![image](https://github.com/cnescatlab/sonar-cnes-report/assets/5272514/cdcfd9c8-5efc-41f4-9d19-21873ef0485e)

#### User environment 

* OS: Centos7, running docker image sonarqube:9.9.1-enterprise
* Project version: 4.2.0

**Comment by Topin2001** [comment]
Hi, 
I was not able to reproduce your bug, but I think that it might be because you're using an outdated version of the plugin, maybe try to use the latest version, it might fix your issue
