### ISSUE TITLE
Have an expiry for the Sonar Auth Tokens, when the plugin creates one for the user

### ISSUE THREAD

**Issue by AravindNSS** [cnescatlab/sonar-cnes-report#367]
Hello,

First of all, thank you for supporting and providing this plugin to the community!

We see that the first time a user generates a report, the plugin creates a token under the user account in the name 'cnes-report'. Now, since Sonarqube has the option to generate tokens with an expiry (30 days, 90 days, etc.), is it possible for the plugin to generate a token with an expiry, say 30/90 days? 
We have a token rotation policy to remind users to refresh their tokens every 90 days and most of the users apart from developers are not aware why they have a token under the name 'cnes-report'.

Is this option available already or can this be done?

Thanks,
Aravind

**Comment by louisjdmartin** [comment]
Hello
At this time this option does not exist, it's a good idea to implement it.

As our resources are limited, we do upgrade on LTS release, feel free to open a merge request ! In my side, I will purpose your idea for the next release.
