### ISSUE TITLE
Unable to generate the report

### ISSUE THREAD

**Issue by srivatsamarichi** [cnescatlab/sonar-cnes-report#369]
#### Describe the bug

> Unable to generate the report on the community server.

#### To reproduce

> Follow the steps outlined to generate the report.

#### Expected behavior

> To generate the report

#### Screenshots & log

> ![Screenshot 2023-10-19 000708](https://github.com/cnescatlab/sonar-cnes-report/assets/13433045/70c4a7fa-c393-41a3-8f42-f47a464bac23).

#### User environment 

> _Please complete the following information._

* OS: [e.g. Windows 11]
* Sonar version: [e.g. 10.1]

**Comment by louisjdmartin** [comment]
Sorry but we did no have enough information to reproduce your bug.
Please re-open issue with more information and a complete procedure to reproduce the error.
