### ISSUE TITLE
Can return only the first 10000 results. 10500th result asked.

### ISSUE THREAD

**Issue by kdknive** [cnescatlab/sonar-cnes-report#371]
#### Describe the bug

I'm using Sonarqube Community Edition with around 20000 projects. I used this plugin on my Enterprise Edition with way less projects than that and it worked flawlessly so I decided to install it on my Community Edition. That's when I came up with this error on the console.
`{
    "errors": [
        {
            "msg": "Can return only the first 10000 results. 10500th result asked."
        }
    ]
}`
I get that there's a limitation to 10000 results applies to web services that are backed by ElasticSearch index, I just wonder if this plugin could find a work around for it.

#### To reproduce

> _Steps to reproduce the behavior._

1. Go to 'CNES Report'
2. Open Network Console

#### Expected behavior

CNES Report showing all of my projects

#### Screenshots & log

![MicrosoftTeams-image (37)](https://github.com/cnescatlab/sonar-cnes-report/assets/48017348/8cd8de3e-6c27-45d3-8ad5-c8ad9424c291)
it just shows loading

![MicrosoftTeams-image (39)](https://github.com/cnescatlab/sonar-cnes-report/assets/48017348/c72cc99b-cfa0-4872-9ef3-fb3211972636)
up until the 20th query, it's all good

![MicrosoftTeams-image (40)](https://github.com/cnescatlab/sonar-cnes-report/assets/48017348/2c05ef5f-15b2-4bc0-9350-8b054a3e6570)
then the 21th query shows the error

#### User environment 

> _Please complete the following information._

* OS: Windows 10
* Sonarqube Community Edition 9.9.2 LTS
* CNES Report plugin 4.2.0

**Comment by Topin2001** [comment]
This limit is SonarQube induce, we won't look for a way to fix it. The project already generate file too long with 10 000 issues, and it will risk to make the sonarqube instance laagy if more request on required to the API
