### ISSUE TITLE
Broken CI

### ISSUE THREAD

**Issue by louisjdmartin** [cnescatlab/sonar-cnes-report#376]
#### Describe the bug

As Sonarcloud changes some permission and force to update from Java 11 to Java 17+, we must upgrade our CI

#### To reproduce

> _Steps to reproduce the behavior._

- Start any CI
- Check SonarQube analysis results

#### Expected behavior

Job should end in success

#### Screenshots & log

See latest CI on dev branch

#### User environment 

Github Actions // Java 11

**Comment by testsys-david** [comment]
I'm using sonarqube version :  10.2.1.78527 and  sonar-cnes-report-4.3.0.jar
Getting error  
This SonarQube version is not supported by this cnesreport version.
In the Compatibility matrix , sonarqube version support is mentioned 9.9 X , I'm using 10.2.1.78527Version of sonarqube, Does the sonar-cnes-report  support the above mentioned Sonarqube  version ??
