### ISSUE TITLE
HTML character issue in generated Docs report 

### ISSUE THREAD

**Issue by aadityasgnr** [cnescatlab/sonar-cnes-report#384]
#### Describe the bug
The Docs report when describing the HTML file issue, The html reserved characters are not getting displayed instaed corresponding Entity name is getting displayed. ex- "&gt_;" in place of '>' , "&nbsp_;" in place of " ".

Is there any way to have html reserved characters displayed in generated docs.
#### To reproduce

> _Steps to reproduce the behavior._

#### Expected behavior

> _A clear and concise description of what you expected to happen._

#### Screenshots & log

> _If applicable, add screenshots and logs to help explain your problem._ **Do not forget to obfuscate them if they contain sensitive data.**.

#### User environment 

> _Please complete the following information._

* OS: [e.g. Windows 10]
* Project version: [e.g. 2.0.0]

**Comment by aadityasgnr** [comment]
![CNES_BUG_Report](https://github.com/cnescatlab/sonar-cnes-report/assets/12480268/b2c28047-0259-4fcb-a243-e72d36e3cd8e)

**Comment by Topin2001** [comment]
Without any reponse, I'm closing this issue, feel free to ask me to re-open it if you encounter this issue again
