### ISSUE TITLE
SonarQube > 10.0 - text and buttons text labels instead of translated text 

### ISSUE THREAD

**Issue by alexpad** [cnescatlab/sonar-cnes-report#388]
After the jar installation in extension/plugins SonarQube web dashboard buttons label and textes are not rendered: only placeholder keys will be diplayed.

OS: Windows 11
Project version: 4.1.3 or 4.3.0

**Comment by Topin2001** [comment]
Hi,
Because the LTS version 10 of sonarqube is not released, we haven't created the plugin for sonarqube version above 9.9 (current LTS).
