### ISSUE TITLE
Sonarqube UI v10.4.1 showing internal element names instead of the proper text because of CNES-REPORT plugin

### ISSUE THREAD

**Issue by belahouel** [cnescatlab/sonar-cnes-report#393]
#### Describe the bug

In Sonarqube version 10.4.1, Sonar UI is showing internal element name instead of the proper text because of the CNES-report plugin

#### To reproduce

1. Deploy SonarQube version 10.4.1
2. Install CNES-report plugin version 4.3.0
3. Go to Quality gates in SonarQube and you will see internal elements instead of text.
4. Go to rules also and you see internal element instead of text

#### Expected behavior

> Should see a proper text instead of internal elements

#### Screenshots & log

![image](https://github.com/cnescatlab/sonar-cnes-report/assets/27809585/617fb33e-c42f-4542-b082-937c8e0a4f23)
![image](https://github.com/cnescatlab/sonar-cnes-report/assets/27809585/9df2cbc4-a0bd-4a7b-9cbe-32db886864f9)

#### User environment 

* OS: Sonar Docker image version 10.4.1
* CNES-report Plugin version: 4.3.0

**Comment by Topin2001** [comment]
Hi,
Because the LTS version 10 of sonarqube is not released, we haven't created the plugin for sonarqube version above 9.9 (current LTS).
