### ISSUE TITLE
Is the current version support SonarCloud?

### ISSUE THREAD

**Issue by chrisyung526** [cnescatlab/sonar-cnes-report#396]
I try to run on CLI 4.3.0 but it said 

[ERROR] Value of parameter 'facets' (files) must be one of: [projects, moduleUuids, fileUuids, assigned_to_me, severities, statuses, issueStatuses, resolutions, rules, assignees, author, directories, languages, tags, types, owaspTop10, sansTop25, cwe, createdAt, sonarsourceSecurity, impactSoftwareQualities, impactSeverities, cleanCodeAttributeCategories]

Did I miss something?

**Comment by Topin2001** [comment]
Hello,
I'm not sure of what you're asking, can you please provide me your sonarqube version ?

**Comment by Sarute** [comment]
Following up on the previous question, does SonarQube 10.5 support version 4.3.0 of the sonar-cnes-report?

**Comment by Topin2001** [comment]
Following a bit of digging, I don't think that sonarcloud is using SonarQube v10.x, it appears they're using the v8.x ....
However, we currently don't have a release for the SQ v10, but I made a MR #397 which should work for SQ 10. Pay attention, it's still in dev, but a pre-release should son be available.
