### ISSUE TITLE
Sonar Cnes report is compatible with sonarqube version of 10.2.1.78527??

### ISSUE THREAD

**Issue by testsys-david** [cnescatlab/sonar-cnes-report#400]
I'm using sonarqube version : 10.2.1.78527 and sonar-cnes-report-4.3.0.jar
Getting error
This SonarQube version is not supported by this cnesreport version.
In the Compatibility matrix , sonarqube version support is mentioned 9.9 X , I'm using 10.2.1.78527 Version of sonarqube, Does the sonar-cnes-report support the above mentioned Sonarqube version ??

**Comment by Topin2001** [comment]
As you mentionned, the report v4.3.0 support version 9.9 LTS, and won't work for 10.2
However, you can give a look to #397 which should 'maybe' work with your SQ version. Keep in mind that this is still a work in progress version.
