### ISSUE TITLE
quality gate is unknown message

### ISSUE THREAD

**Issue by abalasub-wm** [cnescatlab/sonar-cnes-report#403]
> _Before posting a new question, please read the README.md and check existing issues._

I'm unable to download the report and I get the below error. Please assist.

Sonarqube version - Community EditionVersion 10.1 (build 73491)
jar file : - sonar-cnes-report-4.3.0.jar

> _A clear and concise description of what your question is._
`SonarQube online: true
Detected SonarQube version: 10.1.0.73491
[WARNING] This SonarQube version is not supported by this cnesreport version.
[WARNING] For further information, please refer to the compatibility matrix on the project GitHub page.
[ERROR] Quality gate AY-4Unq7JUztMnNgNDyk is unknown.`
> _If applicable, add screenshots and logs to help explain your problem._ **Do not forget to obfuscate them if they contain sensitive data.**.

#### User environment 

> _Please complete the following information._

* OS: [e.g. Windows 10]
* Project version: [e.g. 2.0.0]

**Comment by Topin2001** [comment]
As mentionned in the compatibility matrix, the sonar-cnes-report only support SQ version until 9.9 LTS.
If you want to use it for SQ 10.x.x, you can use the latest pre-release, which should work. Pay attention, this one is still in dev and you might encounter some issues.
