### ISSUE TITLE
Unable to get the cnes report in the UI 

### ISSUE THREAD

**Issue by vadhiarpraneeth** [cnescatlab/sonar-cnes-report#404]
#### Describe the bug

I have installed the cnes plugin but in the UI i'm not able to see the cnes report option (more section). When i check the es.log it is showing no plugins were installed, i have restarted the sonarqube server still i'm facing the same issue.

**Please find the logs below**

#### Screenshots & log

2024.07.03 11:16:27 INFO  es[][o.e.n.Node] initialized
2024.07.03 11:16:27 INFO  es[][o.e.n.Node] starting ...
2024.07.03 11:16:27 INFO  es[][o.e.t.TransportService] publish_address {127.0.0.1:33989}, bound_addresses {127.0.0.1:33989}
2024.07.03 11:16:27 INFO  es[][o.e.b.BootstrapChecks] explicitly enforcing bootstrap checks
2024.07.03 11:16:27 INFO  es[][o.e.c.c.Coordinator] cluster UUID [QIR7xNTkTpysg2ChnOH2nw]
2024.07.03 11:16:28 INFO  es[][o.e.c.s.MasterService] elected-as-master ([1] nodes joined)[{sonarqube}{WPN1a7MXRBqmD7E9tKrPRw}{Ewz6PcZlRL-1l0wCIhyTrA}{127.0.0.1}{127.0.0.1:33989}{cdfhimrsw} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 32489, version: 64911, delta: master node changed {previous [], current [{sonarqube}{WPN1a7MXRBqmD7E9tKrPRw}{Ewz6PcZlRL-1l0wCIhyTrA}{127.0.0.1}{127.0.0.1:33989}{cdfhimrsw}]}
2024.07.03 11:16:28 INFO  es[][o.e.c.s.ClusterApplierService] master node changed {previous [], current [{sonarqube}{WPN1a7MXRBqmD7E9tKrPRw}{Ewz6PcZlRL-1l0wCIhyTrA}{127.0.0.1}{127.0.0.1:33989}{cdfhimrsw}]}, term: 32489, version: 64911, reason: Publication{term=32489, version=64911}
2024.07.03 11:16:28 INFO  es[][o.e.h.AbstractHttpServerTransport] publish_address {127.0.0.1:9001}, bound_addresses {127.0.0.1:9001}
2024.07.03 11:16:28 INFO  es[][o.e.n.Node] started
2024.07.03 11:16:28 INFO  es[][o.e.g.GatewayService] recovered [0] indices into cluster_state
2024.07.03 11:16:30 INFO  es[][o.e.n.Node] stopping ...
2024.07.03 11:16:30 INFO  es[][o.e.n.Node] stopped
2024.07.03 11:16:30 INFO  es[][o.e.n.Node] closing ...
2024.07.03 11:16:30 INFO  es[][o.e.n.Node] closed
2024.07.03 11:16:35 INFO  es[][o.e.n.Node] version[7.17.8], pid[2175237], build[default/tar/120eabe1c8a0cb2ae87cffc109a5b65d213e9df1/2022-12-02T17:33:09.727072865Z], OS[Linux/5.15.0-113-generic/amd64], JVM[Ubuntu/OpenJDK 64-Bit Server VM/17.0.11/17.0.11+9-Ubuntu-122.04.1]
2024.07.03 11:16:35 INFO  es[][o.e.n.Node] JVM home [/usr/lib/jvm/java-17-openjdk-amd64]
2024.07.03 11:16:35 INFO  es[][o.e.n.Node] JVM arguments [-XX:+UseG1GC, -Djava.io.tmpdir=/opt/sonarqube/temp, -XX:ErrorFile=/opt/sonarqube/logs/es_hs_err_pid%p.log, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djna.tmpdir=/opt/sonarqube/temp, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=COMPAT, -Dcom.redhat.fips=false, -Des.enforce.bootstrap.checks=true, -Xmx512m, -Xms512m, -XX:MaxDirectMemorySize=256m, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/opt/sonarqube/elasticsearch, -Des.path.conf=/opt/sonarqube/temp/conf/es, -Des.distribution.flavor=default, -Des.distribution.type=tar, -Des.bundled_jdk=false]
2024.07.03 11:16:36 INFO  es[][o.e.p.PluginsService] loaded module [analysis-common]
2024.07.03 11:16:36 INFO  es[][o.e.p.PluginsService] loaded module [lang-painless]
2024.07.03 11:16:36 INFO  es[][o.e.p.PluginsService] loaded module [parent-join]
2024.07.03 11:16:36 INFO  es[][o.e.p.PluginsService] loaded module [reindex]
2024.07.03 11:16:36 INFO  es[][o.e.p.PluginsService] loaded module [transport-netty4]
2024.07.03 11:16:36 INFO  es[][o.e.p.PluginsService] no plugins loaded
2024.07.03 11:16:36 INFO  es[][o.e.e.NodeEnvironment] using [1] data paths, mounts [[/ (/dev/mapper/ubuntu--vg-lv--0)]], net usable_space [46.4gb], net total_space [68.3gb], types [ext4]
2024.07.03 11:16:36 INFO  es[][o.e.e.NodeEnvironment] heap size [512mb], compressed ordinary object pointers [true]
2024.07.03 11:16:36 INFO  es[][o.e.n.Node] node name [sonarqube], node ID [WPN1a7MXRBqmD7E9tKrPRw], cluster name [sonarqube], roles [data_frozen, master, remote_cluster_client, data, data_content, data_hot, data_warm, data_cold, ingest]

#### User environment 

> _Please complete the following information._

* OS: ubuntu 22.04
* Project version: cnes-report-4.3.0
* sonarqube version: v10.5

**Comment by Topin2001** [comment]
As mentionned in the READ-ME file, in the compatibility matrix, you can see that the version 4.3.0 support only SQ 9.9 LTS. I recommend you to use this SQ version. However, if you want to use SQ 10, you can use the pre-release version 5.0.0 of the plugin. Be aware that with this version you might encounter some issue. If that append, please open a new issue, with the log of sonarqube
Cheers, Thomas
