### ISSUE TITLE
unable to see the option cnes report in the UI for sonarqube 10.6

### ISSUE THREAD

**Issue by lakshmi123456789412** [cnescatlab/sonar-cnes-report#405]
#### Describe the bug

> _A clear and concise description of what the bug is._

#### To reproduce

I have installed the cnes jar in the plugins latest 5.0.0 but still i am not able to see the option cnes in the more option in the UI. After installing the jar i have stopped and started the sonarqube still not able to find the option
#### Screenshots & log
please find the below path which i have installed cnes plugin and logs
root@server:/opt/sonarqube/extensions/plugins# ls -ltr
total 42952
-rw-r--r-- 1 sonarqube sonarqube      737 Feb  3  2023 README.txt
-rw-r--r-- 1 sonarqube sonarqube 43976185 Jul  5 10:29 sonar-cnes-report-5.0.0.jar

root@server:/opt/sonarqube/logs# tail -f es.log 
2024.07.05 10:44:59 INFO  es[][o.e.p.PluginsService] loaded module [reindex]
2024.07.05 10:44:59 INFO  es[][o.e.p.PluginsService] loaded module [transport-netty4]
2024.07.05 10:44:59 INFO  es[][o.e.p.PluginsService] no plugins loaded
2024.07.05 10:44:59 INFO  es[][o.e.e.NodeEnvironment] using [1] data paths, mounts [[/ (/dev/mapper/ubuntu--vg-lv--0)]], net usable_space [46.1gb], net total_space [68.3gb], types [ext4]
2024.07.05 10:44:59 INFO  es[][o.e.e.NodeEnvironment] heap size [512mb], compressed ordinary object pointers [true]
2024.07.05 10:45:00 INFO  es[][o.e.n.Node] node name [sonarqube], node ID [WPN1a7MXRBqmD7E9tKrPRw], cluster name [sonarqube], roles [data_frozen, master, remote_cluster_client, data, data_content, data_hot, data_warm, data_cold, ingest]
2024.07.05 10:45:04 INFO  es[][o.e.t.NettyAllocator] creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=256kb, factors={es.unsafe.use_unpooled_allocator=null, g1gc_enabled=true, g1gc_region_size=1mb, heap_size=512mb}]
2024.07.05 10:45:04 INFO  es[][o.e.i.r.RecoverySettings] using rate limit [40mb] with [default=40mb, read=0b, write=0b, max=0b]
2024.07.05 10:45:04 INFO  es[][o.e.d.DiscoveryModule] using discovery type [zen] and seed hosts providers [settings]
2024.07.05 10:45:05 INFO  es[][o.e.g.DanglingIndicesState] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
2024.07.05 10:45:05 INFO  es[][o.e.n.Node] initialized
2024.07.05 10:45:05 INFO  es[][o.e.n.Node] starting ...
2024.07.05 10:45:05 INFO  es[][o.e.t.TransportService] publish_address {127.0.0.1:36483}, bound_addresses {127.0.0.1:36483}
2024.07.05 10:45:06 INFO  es[][o.e.b.BootstrapChecks] explicitly enforcing bootstrap checks
2024.07.05 10:45:06 INFO  es[][o.e.c.c.Coordinator] cluster UUID [QIR7xNTkTpysg2ChnOH2nw]

> _If applicable, add screenshots and logs to help explain your problem._ **Do not forget to obfuscate them if they contain sensitive data.**.

#### User environment :

> _Please complete the following information._

* OS: [e.g. Windows 10] ubuntu 22.04

**Comment by Topin2001** [comment]
Hi,
I've tried the plugin for the SonarQube 10.6 version and it's working perfectly on my side.
Can you please provide me wih your exact version and build number of sonarqube ? 
Can you please send me also the output of sonarqube, and not only of Es?
Thanks

**Comment by Topin2001** [comment]
Without any reponse, I'm closing this issue, feel free to ask me to re-open it if you encounter this issue again
