### ISSUE TITLE
Able to see the option cnes report but unable to download the report  getting 500 server

### ISSUE THREAD

**Issue by lakshmi123456789412** [cnescatlab/sonar-cnes-report#406]
#### Describe the bug

> _A clear and concise description of what the bug is._

I have installed sonarqube 9.6 and cnes jar version 4.1.2 and in the UI  i am able to see the cnes report option when i am submitting the option to download the report getting 500 error

#### To reproduce

> _Steps to reproduce the behavior._

#### Expected behavior

> _A clear and concise description of what you expected to happen._

#### Screenshots & log

> _If applicable, add screenshots and logs to help explain your problem._ **Do not forget to obfuscate them if they contain sensitive data.**.

#### User environment 

> _Please complete the following information._

* OS: [e.g. Windows 10] ubuntu 22.04
* Project version: [e.g. 2.0.0]

**Comment by Topin2001** [comment]
As shown in the version matrix,; we do not support SQ9.6 with our plugin, please install the 9.9 LTS and the 4.3.0 version of the plugin to fix this issue
