### ISSUE TITLE
Able to see the option cnes report but unable to download the report getting check your token

### ISSUE THREAD

**Issue by lakshmi123456789412** [cnescatlab/sonar-cnes-report#407]
#### Describe the bug

> _A clear and concise description of what the bug is._
\  
I have tried sonarqube verion 8.9.10 build number 61524 and cnes plugin 3.2.0  and i am able to see the cnes report plugin in the UI and  when i am downloading the report getting the below error
{
    "error": "This project can't be exported, please check your token."
}

#### Screenshots & log

please find the logs

tail -f sonar.20240709.log 
Jul 09, 2024 4:31:41 AM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube online: true
Jul 09, 2024 4:31:41 AM fr.cnes.sonar.report.ReportCommandLine execute
INFO: Detected SonarQube version: 8.9.10
Jul 09, 2024 4:33:32 AM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube URL:
http://localhost:9000/
Jul 09, 2024 4:33:32 AM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube online: true
Jul 09, 2024 4:33:32 AM fr.cnes.sonar.report.ReportCommandLine execute
INFO: Detected SonarQube version: 8.9.10

ail -f es.log
2024.07.08 12:18:23 INFO  es[][o.e.n.Node] starting ...
2024.07.08 12:18:23 INFO  es[][o.e.t.TransportService] publish_address {127.0.0.1:34383}, bound_addresses {127.0.0.1:34383}
2024.07.08 12:18:24 INFO  es[][o.e.b.BootstrapChecks] explicitly enforcing bootstrap checks
2024.07.08 12:18:24 INFO  es[][o.e.c.c.Coordinator] cluster UUID [P83eOicqT5aT9IYImycMzA]
2024.07.08 12:18:24 INFO  es[][o.e.c.s.MasterService] elected-as-master ([1] nodes joined)[{sonarqube}{VT38ilTDQGuv24OkZ-HBFw}{WqFc6ptAQ9Oe1614RAf76g}{127.0.0.1}{127.0.0.1:34383}{cdfhimrsw} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 3, version: 64, delta: master node changed {previous [], current [{sonarqube}{VT38ilTDQGuv24OkZ-HBFw}{WqFc6ptAQ9Oe1614RAf76g}{127.0.0.1}{127.0.0.1:34383}{cdfhimrsw}]}
2024.07.08 12:18:24 INFO  es[][o.e.c.s.ClusterApplierService] master node changed {previous [], current [{sonarqube}{VT38ilTDQGuv24OkZ-HBFw}{WqFc6ptAQ9Oe1614RAf76g}{127.0.0.1}{127.0.0.1:34383}{cdfhimrsw}]}, term: 3, version: 64, reason: Publication{term=3, version=64}
2024.07.08 12:18:24 INFO  es[][o.e.h.AbstractHttpServerTransport] publish_address {127.0.0.1:9001}, bound_addresses {127.0.0.1:9001}
2024.07.08 12:18:24 INFO  es[][o.e.n.Node] started
2024.07.08 12:18:25 INFO  es[][o.e.g.GatewayService] recovered [7] indices into cluster_state
2024.07.08 12:18:28 INFO  es[][o.e.c.r.a.AllocationService] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[metadatas][0]]]).

#### User environment 

> _Please complete the following information._

* OS: [e.g. Windows 10] Ubuntu 22.04
* Project version: [e.g. 2.0.0]

**Comment by Topin2001** [comment]
As shown in the version matrix, we support SQ8.9 with our plugin, please install the 4.1.x version of the plugin to fix this issue
