### ISSUE TITLE
CNES Plugin For SonarQube Developer edition

### ISSUE THREAD

**Issue by chaitanyapendyala** [cnescatlab/sonar-cnes-report#408]
#### Describe the bug
I have Installed the cnes plugin 5.0.0 for My SonarQube Developer Edition 10.5.1 while generating the report i am getting the error as 
"500 - The request timed out.
The web server failed to respond within the specified time." 

I tried with the 4.3.0 also still getting the same error
<img width="482" alt="Screenshot 2024-07-16 at 5 46 13 PM" src="https://github.com/user-attachments/assets/b38ed37a-48df-4809-b9ff-b9b012851f53">

#### Screenshots & log

> _If applicable, add screenshots and logs to help explain your problem._ **Do not forget to obfuscate them if they contain sensitive data.**.

#### User environment 
SonarQube is installed on Azure App Service
> _Please complete the following information._
<img width="909" alt="Screenshot 2024-07-16 at 5 41 21 PM" src="https://github.com/user-attachments/assets/e1d25350-6527-4779-b8fc-4dbc69429d1b">

**Comment by Topin2001** [comment]
Hi,
I've done a few tests on my side, but I wasn't able to reproduce your error,
Can you please give me the sonarqube logs from the moment of the error ?
Thanks

**Comment by chaitanyapendyala** [comment]
I have huge amount of code lines is that is a reason for taking time to generate the report and getting 500 error timeout

**Comment by Topin2001** [comment]
Actually, I'm not asking for the sonarqube analysis, but for tue logs of the SonarQube App itself, which should be available in your azure output

**Comment by chaitanyapendyala** [comment]
Hi @Topin2001 as per my source code  i excluded the some files and generated the report it's working now
Only if i have a huge amount of code is being scanned and then taking long time to generate the report and then timeout error.

**Comment by Topin2001** [comment]
Hi @chaitanyapendyala , without the exact output of the SonarQube server, I'll not be able to look more in the issue.
However, I think that your issue is due to the SonarQube limit to export no more than 15000 errors. If this is the case, we'll not be able to fix this, because it's out of our scope of action.

**Comment by chaitanyapendyala** [comment]
thanks @Topin2001  you can close this
