### ISSUE TITLE
Does it support SQ 10.7.0?

### ISSUE THREAD

**Issue by IrfanNian** [cnescatlab/sonar-cnes-report#421]
I am running the latest version of SonarQube 10.7.0 as a VM from Bitnami. I got everything running, however whenever I tried to put the cnes .jar file in the /opt/..../plugins/ directory, my SQ will stop to work - even after restarting the VM/services. It will show "503 Service Unavailable". When I remove the .jar file in the plugins directory, SQ works as per normal. Could this be due to cnes not supporting 10.7.0?

**Comment by louisjdmartin** [comment]
Hi,
Not really for now,
We have made a first version with sonarqube 10 to start work on next sonarqube LTS but we are waiting for the next LTS for a full support of Sonarqube 10.x.
